### ISSUE TITLE
Travis CI log:  `initialize': No such file or directory @ rb_sysopen - app/build/outputs/apk/app-release.apk (Errno::ENOENT)

### ISSUE THREAD

**Issue by fandean** [FanDean/android_Travis_CI_Test#2]
# 没有该文件或目录的两种情况

```log
/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:86:in `initialize': No such file or directory @ rb_sysopen - app/build/outputs/apk/app-release.apk (Errno::ENOENT)
```

```
/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:86:in `initialize': No such file or directory @ rb_sysopen - app/build/outputs/apk/app-debug.apk (Errno::ENOENT)
```

**Comment by fandean** [comment]
通过在 .travis.yml 中添加如下语句，以查看文件夹内容：

```yml
before_deploy:
  - ls app/build/outputs/apk/
```
log输出：
```shell
$ ls app/build/outputs/apk/
app-release-unsigned.apk
```
更改 .travis.yml 原来的
```yml
deploy:
  file: app/build/outputs/apk/app-debug.apk
```
为
```yml
deploy:
  file: app/build/outputs/apk/app-release-unsigned.apk
```
